spring:
  application:
    name: file-upload
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://172.18.0.3:5432/file_upload
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: default
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

minio:
  url: http://localhost:9000
  access-key: bo1ilnqokhtCjO5Rq5mB
  secret-key: Y62obZUmDThTXWLsKZGb5jxx8WpDIGZ5NmYTDi5r
  buckets:
    kyc-bucket-name: file-upload
  region: us-east-1
  secure: false
  port: 9000