#!/bin/bash

export REDIS_HOST=127.0.0.1
export REDIS_PORT=6379
export REDIS_MODE_CLUSTER=true
export SPRING_DATA_CLUSTER_CACHE_NAME_OTP_TTL=30
export SPRING_DATA_CLUSTER_CACHE_NAME_OTP_MAX_SIZE=100
export REDIS_CLUSTER_NODES=palindrome-redis:6379
export REDIS_CLUSTER_TOPOLOGY_REFRESH_PERIOD_IN_SECONDS=60
export REDIS_CONNECTION_USES_SSL=true
export REDIS_TIMEOUT=1000

./gradlew bootRun --args='--debug'