scrape_configs:
  - job_name: 'prometheus-example'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'prometheus-example'